"""initial_schema

Revision ID: b47f479c9504
Revises: 
Create Date: 2026-04-20 21:45:13.706679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b47f479c9504'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rights_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('territories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_table('asset_fingerprints',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('phash', sa.String(length=256), nullable=True),
    sa.Column('whash', sa.String(length=256), nullable=True),
    sa.Column('chromaprint', sa.LargeBinary(), nullable=True),
    sa.Column('watermark_payload', sa.String(length=64), nullable=True),
    sa.Column('embedding_vector_hash', sa.String(length=128), nullable=True),
    sa.Column('fingerprinted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('violations_found', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_asset_id'), 'scan_runs', ['asset_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('discovered_url', sa.String(length=2048), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('infringement_type', sa.String(length=50), nullable=True),
    sa.Column('transformation_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('estimated_reach', sa.Integer(), nullable=True),
    sa.Column('rights_territory_violation', sa.Boolean(), nullable=False),
    sa.Column('triage_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_asset_id'), 'violations', ['asset_id'], unique=False)
    op.create_table('dmca_notices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('violation_id', sa.Uuid(), nullable=False),
    sa.Column('notice_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dmca_notices_violation_id'), 'dmca_notices', ['violation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dmca_notices_violation_id'), table_name='dmca_notices')
    op.drop_table('dmca_notices')
    op.drop_index(op.f('ix_violations_asset_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_scan_runs_asset_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_table('asset_fingerprints')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('tasks')
    op.drop_table('organizations')
    # ### end Alembic commands ###
